name: CI - JobTracker

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Back-end:
    name: Back-end
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do codigo
        uses: actions/checkout@v4
      - name: Configurar Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Instalar dependencias
        working-directory: Back-end
        run: npm install
      - name: Rodar testes
        working-directory: Back-end
        run: npm test -- --run

  deploy:
    name: Deploy VPS
    runs-on: ubuntu-latest
    needs: [Back-end]
    if: github.event_name == 'push'
    steps:
      - name: Deploy na VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            cd ~/projetos/JobTracker
            git pull origin main
            cd Back-end
            npm ci
            npx tsc
            pm2 restart jobtracker-backend
            cd ../Front-end/job-tracker
            npm ci
            ng build --configuration production
  
  
